#!/usr/bin/env bash

# =========================================================================== #
#                                                                             #
# This script can be employed to automatically copy evolution files           #
# from different sub-folders (as the one generated by execution               #
# on the cluster) into a single one, which can then be used                   #
# by data_plotter.py script to generate comparison charts                     #
#                                                                             #
# input parameter -> the parent folder where the folders produced             #
#                    by each experiment run are stored                        #
#                                                                             #
# execution -> sh merge_seeds_run.sh <parent-folder-results>                  #
#                                                                             #
# e.g.  ./merge_seeds_run.sh ../../results/cluster_res/13_5seed               #
#                                                                             #
# =========================================================================== #

data_folder=$1
exp_counter=0

# create sub-folder that will contain all the data coming from different experiment runs
out_folder=${data_folder}/all_runs_data
mkdir -p ${out_folder}

for sub_folder in ${data_folder}/[0-9]*;
do
    for exp_file in ${sub_folder}/evo_*_sim_*.json
    do
        echo $exp_file
        out_name=`echo $(basename -- ${exp_file}) | sed -e "s/.json/_${exp_counter}.json/g"`
        echo $out_name
        cp ${exp_file} ${out_folder}/${out_name}

        exp_counter=$((exp_counter + 1))
    done
done